package classify

import (
	"strings"
	"testing"

	"github.com/ShadowOpenTech/codeprint/internal/detect"
)

func TestIsTest(t *testing.T) {
	yes := []string{
		"foo_test.go", "pkg/foo_test.go",
		"util.spec.ts", "util.test.js", "comp.spec.tsx",
		"FooTest.java", "BarTests.java", "BazIT.java",
		"test_app.py", "app_test.py",
		"model_spec.rb", "model_test.rb",
		"tests/whatever.py", "src/__tests__/x.js", "spec/x.rb",
	}
	for _, p := range yes {
		if !IsTest(p) {
			t.Errorf("IsTest(%q) = false, want true", p)
		}
	}
	no := []string{"foo.go", "app.py", "index.js", "src/main/App.java", "README.md"}
	for _, p := range no {
		if IsTest(p) {
			t.Errorf("IsTest(%q) = true, want false", p)
		}
	}
}

func TestIsMinified(t *testing.T) {
	if !isMinified("a.min.js", nil) {
		t.Error(".min.js should be minified by extension")
	}
	if !isMinified("a.min.css", nil) {
		t.Error(".min.css should be minified by extension")
	}
	long := []byte(strings.Repeat("a=1;", 400))
	if !isMinified("packed.js", long) {
		t.Error("long single line should be minified by heuristic")
	}
	if isMinified("normal.js", []byte("a = 1;\nb = 2;\n")) {
		t.Error("normal multi-line file should not be minified")
	}
	if isMinified("empty.js", nil) {
		t.Error("empty non-.min file should not be minified")
	}
}

func TestHasGeneratedHeader(t *testing.T) {
	if !hasGeneratedHeader([]byte("// Code generated by tool. DO NOT EDIT.\npackage x\n")) {
		t.Error("Go generated header should match")
	}
	if !hasGeneratedHeader([]byte("/* @generated */\nx\n")) {
		t.Error("@generated should match")
	}
	// Prose mentioning the phrase must not trigger (the README false-positive).
	if hasGeneratedHeader([]byte("This generated file uses a DO NOT EDIT header marker.\n")) {
		t.Error("prose should not match generated header")
	}
	if hasGeneratedHeader(nil) {
		t.Error("empty content should not match")
	}
	// A build-tag line then the marker (within the head window) should match.
	if !hasGeneratedHeader([]byte("//go:build linux\n\n// Code generated by x. DO NOT EDIT.\npackage y\n")) {
		t.Error("header after build tag should match")
	}
	// The marker appearing DEEP in a file (e.g. a string literal in a test) must
	// NOT match — this is the classify_test.go false-positive class.
	deep := []byte("package x\n" + "var s = 1\n" + "func f() {}\n" + "func g() {}\n" +
		"func h() {}\n" + "// Code generated x DO NOT EDIT (this is a string in a test)\n")
	if hasGeneratedHeader(deep) {
		t.Error("marker deep in the file should NOT be treated as a generated header")
	}
}

func TestClassifyPriorityAndFlags(t *testing.T) {
	// Generated test file: kind=generated (higher priority), flags=[test].
	kind, flags := Classify("foo_test.go", []byte("// Code generated x DO NOT EDIT.\n"), detect.Result{})
	if kind != Generated {
		t.Errorf("kind = %q, want generated", kind)
	}
	if len(flags) != 1 || flags[0] != FlagTest {
		t.Errorf("flags = %v, want [test]", flags)
	}

	// Binary wins over everything.
	if k, _ := Classify("x", nil, detect.Result{IsBinary: true}); k != Binary {
		t.Errorf("binary priority: got %q", k)
	}
	// Minified wins over vendored (explicit refinement).
	if k, _ := Classify("a.min.js", nil, detect.Result{IsVendor: true}); k != Minified {
		t.Errorf("minified should beat vendored: got %q", k)
	}
	// Plain source.
	if k, f := Classify("main.go", []byte("package main\n"), detect.Result{}); k != Source || len(f) != 0 {
		t.Errorf("source: got %q flags %v", k, f)
	}
}

func TestCountsLOC(t *testing.T) {
	for _, k := range []string{Binary, Vendored, Minified} {
		if CountsLOC(k) {
			t.Errorf("%s should not count LOC", k)
		}
	}
	for _, k := range []string{Source, Test, Generated} {
		if !CountsLOC(k) {
			t.Errorf("%s should count LOC", k)
		}
	}
}
